# Generated by Django 5.2.15 on 2026-07-03 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('writer_name', models.CharField(max_length=20, verbose_name='작성자 표시')),
                ('book_title', models.CharField(max_length=100, verbose_name='책 제목')),
                ('book_author', models.CharField(max_length=50, verbose_name='저자')),
                ('post_text', models.TextField(verbose_name='추천 이유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '추천글',
                'verbose_name_plural': '추천글',
                'ordering': ['-created_at'],
            },
        ),
    ]
