# Generated by Django 5.2.15 on 2026-07-08 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 사용자'),
        ),
    ]
